language: node_js
node_js:
  - '10'
  - '12'
  - '14'
cache:
  directories:
    - 'node_modules'

script:
  # - npm run test
  - npm run build

deploy:
  provider: npm
  email: jonas.m.andreasson@gmail.com
  api_token: NPM_TOKEN
  edge: true
  on:
    branch: main
